when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        persistence:
            # Flush only once per call of `PersistentObjectFactory::create()`
            flush_once: true

#    services:
#        App\Tests\Factory\:
#            resource: '%kernel.project_dir%/tests/Factory/'
#            autowire: true
#            autoconfigure: true

when@test: *dev
